live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xF8BD96"
index = 16

[[colors.indexed_colors]]
color = "0xF5E0DC"
index = 17

[colors.bright]
black = "0x988BA2"
blue = "0x96CDFB"
cyan = "0x89DCEB"
green = "0xABE9B3"
magenta = "0xF5C2E7"
red = "0xF28FAD"
white = "0xD9E0EE"
yellow = "0xFAE3B0"

[colors.cursor]
cursor = "0xF5E0DC"
text = "0x1E1D2F"

[colors.normal]
black = "0x6E6C7E"
blue = "0x96CDFB"
cyan = "0x89DCEB"
green = "0xABE9B3"
magenta = "0xF5C2E7"
red = "0xF28FAD"
white = "0xD9E0EE"
yellow = "0xFAE3B0"

[colors.primary]
background = "0x1E1D2F"
foreground = "0xD9E0EE"

[cursor.style]
blinking = "Never"

[font]
size = 15.0

[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

# [[keyboard.bindings]]
# action = "Paste"
# key = "V"
# mods = "Control|Shift"
#
# [[keyboard.bindings]]
# action = "Copy"
# key = "C"
# mods = "Control|Shift"
#
# [[keyboard.bindings]]
# action = "ResetFontSize"
# key = "Key0"
# mods = "Control"
#
# [[keyboard.bindings]]
# action = "IncreaseFontSize"
# key = "Equals"
# mods = "Control"
#
# [[keyboard.bindings]]
# action = "IncreaseFontSize"
# key = "Add"
# mods = "Control"
#
# [[keyboard.bindings]]
# action = "DecreaseFontSize"
# key = "Subtract"
# mods = "Control"
#
# [[keyboard.bindings]]
# action = "DecreaseFontSize"
# key = "Minus"
# mods = "Control"
#
# [[keyboard.bindings]]
# action = "SpawnNewInstance"
# key = "N"
# mods = "Control"

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
dynamic_title = false
opacity = 0.9

[window.padding]
x = 2
y = 2
