#!/bin/sh
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'
alias reload='source ~/.config/zsh/.zshrc'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Colorize ls output
# alias ls='ls --color=auto'
# alias la='ls -a'
# alias ll='ls -l'
# alias lla='ls -la'

# exa instead of ls
alias ls='exa --color=always --grid --icons --group-directories-first'
alias la='exa -a --color=always --grid --icons --group-directories-first'
alias ll='exa -l --header --color=always --grid --icons --group-directories-first'
alias lla='exa -la --header --color=always --grid --icons --group-directories-first'

# bat instead of cat
alias cat='bat'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# to show unicode characters in tmux sessions
alias tmux='tmux -u'

# easier to read disk
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB

alias m="git checkout master"
alias mm="git checkout main"

