#! /bin/sh

# Autostart
xsetroot -cursor_name left_ptr
# nm-applet &
# blueman-manager &
picom &
# flameshot &
# polybar example &
dunst &
# xfce4-clipman &
# feh --bg-fill --randomize ~/Pictures/wallpapers/*
nitrogen --set-zoom-fill --random ~/Pictures/wallpapers/

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
