#! /bin/sh

# Autostart
nm-applet &
blueman-manager &
picom -b --experimental-backends &
flameshot &
polybar example &
dunst &
xfce4-clipman &
feh --bg-fill --randomize ~/Pictures/wallpapers/*

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
